"""empty message

Revision ID: 12ec233f1134
Revises: 3aa554b14320
Create Date: 2022-10-12 10:02:27.583165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ec233f1134'
down_revision = '3aa554b14320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('subtitle', sa.Text(), nullable=False))
    op.add_column('news', sa.Column('image', sa.String(length=200), nullable=False))
    op.add_column('news', sa.Column('image_secondary', sa.String(length=200), nullable=False))
    op.add_column('news', sa.Column('image_preview', sa.String(length=200), nullable=False))
    op.add_column('news', sa.Column('public_id_secondary', sa.String(length=100), nullable=False))
    op.drop_column('news', 'url_preview')
    op.drop_column('news', 'url_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('url_image', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('news', sa.Column('url_preview', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('news', 'public_id_secondary')
    op.drop_column('news', 'image_preview')
    op.drop_column('news', 'image_secondary')
    op.drop_column('news', 'image')
    op.drop_column('news', 'subtitle')
    # ### end Alembic commands ###
