"""empty message

Revision ID: 13dbe2fe06a3
Revises: 12ec233f1134
Create Date: 2022-10-13 08:56:31.666286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13dbe2fe06a3'
down_revision = '12ec233f1134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('highlighted', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'highlighted')
    # ### end Alembic commands ###
