"""empty message

Revision ID: 3aa554b14320
Revises: f09488b49c55
Create Date: 2022-10-11 23:50:28.625098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa554b14320'
down_revision = 'f09488b49c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('complete', sa.Text(), nullable=False),
    sa.Column('url_image', sa.String(length=200), nullable=False),
    sa.Column('url_preview', sa.String(length=200), nullable=False),
    sa.Column('public_id_image', sa.String(length=100), nullable=False),
    sa.Column('public_id_preview', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
