"""empty message

Revision ID: f09488b49c55
Revises: 2cc1e997da7d
Create Date: 2022-10-11 21:25:51.786594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09488b49c55'
down_revision = '2cc1e997da7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unore')
    # ### end Alembic commands ###
